apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-monitor
spec:
  selector:
    matchLabels:
      app: event-monitor
  template:
    metadata:
      labels:
        app: event-monitor
    spec:
      containers:
      - name: event-monitor
        image: escoffier/event-monitor:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /host/run/containerd/containerd.sock
          name: containerd-socket
      volumes:
      - hostPath:
          path: /run/containerd/containerd.sock
          type: ""
        name: containerd-socket

